In [1]:
import torch
import numpy as np

In [14]:
t1 = torch.randint(100,(4,4))
t2 = torch.randint(100,(4,4))
t3 = torch.randint(100,(4,4))
print(t1,t1.shape)
print(t2,t2.shape)
print(t3,t2.shape)

tensor([[76, 51, 48, 77],
        [37, 30, 55, 14],
        [ 4, 71, 77,  7],
        [25,  4, 47, 65]]) torch.Size([4, 4])
tensor([[40, 18, 89, 53],
        [11, 44,  6,  5],
        [49, 50, 31, 42],
        [94, 51, 26, 59]]) torch.Size([4, 4])
tensor([[73, 97, 54, 34],
        [99,  2, 85, 12],
        [83, 53, 30, 32],
        [63, 70, 16, 65]]) torch.Size([4, 4])


In [12]:
#comnbining tensors
tensor_new = torch.stack((t1,t2,t3))
tensor_new.shape

torch.Size([3, 4, 4])

In [17]:
tensor_new  = tensor_new.reshape(3,1,4,4)
tensor_new

tensor([[[[24, 58, 53, 34],
          [55, 59, 49,  5],
          [95, 43,  1, 82],
          [45, 35, 61, 41]]],


        [[[95,  6, 34, 74],
          [12, 17, 84, 31],
          [30, 48, 78,  2],
          [51, 43, 21, 50]]],


        [[[19, 45, 93, 62],
          [98, 35, 97, 53],
          [21,  2, 59, 73],
          [22, 58, 92, 64]]]])

In [22]:
tensor_new.flatten(start_dim=1)

tensor([[24, 58, 53, 34, 55, 59, 49,  5, 95, 43,  1, 82, 45, 35, 61, 41],
        [95,  6, 34, 74, 12, 17, 84, 31, 30, 48, 78,  2, 51, 43, 21, 50],
        [19, 45, 93, 62, 98, 35, 97, 53, 21,  2, 59, 73, 22, 58, 92, 64]])