In [1]:
import torch
import numpy as np

In [3]:
t1 = torch.randint(100,(4,4))
t2 = torch.randint(100,(4,4))
t3 = torch.randint(100,(4,4))
print(t1,t1.shape)
print(t2,t2.shape)
print(t3,t2.shape)

tensor([[28, 94, 48, 21],
        [19,  9, 94, 84],
        [58, 45, 68, 74],
        [38, 34, 38,  7]]) torch.Size([4, 4])
tensor([[99, 67,  0, 94],
        [38, 91, 83, 86],
        [79,  8,  0, 13],
        [56, 67, 62, 92]]) torch.Size([4, 4])
tensor([[14, 85, 77, 89],
        [ 9, 44, 15, 36],
        [40, 29,  1, 20],
        [ 5, 65, 58, 73]]) torch.Size([4, 4])


In [4]:
#comnbining tensors
tensor_new = torch.stack((t1,t2,t3))
print(tensor_new.shape)
print(tensor_new)

torch.Size([3, 4, 4])
tensor([[[28, 94, 48, 21],
         [19,  9, 94, 84],
         [58, 45, 68, 74],
         [38, 34, 38,  7]],

        [[99, 67,  0, 94],
         [38, 91, 83, 86],
         [79,  8,  0, 13],
         [56, 67, 62, 92]],

        [[14, 85, 77, 89],
         [ 9, 44, 15, 36],
         [40, 29,  1, 20],
         [ 5, 65, 58, 73]]])


In [5]:
tensor_new  = tensor_new.reshape(3,1,4,4)
print(tensor_new.shape)
print(tensor_new)

torch.Size([3, 1, 4, 4])
tensor([[[[28, 94, 48, 21],
          [19,  9, 94, 84],
          [58, 45, 68, 74],
          [38, 34, 38,  7]]],


        [[[99, 67,  0, 94],
          [38, 91, 83, 86],
          [79,  8,  0, 13],
          [56, 67, 62, 92]]],


        [[[14, 85, 77, 89],
          [ 9, 44, 15, 36],
          [40, 29,  1, 20],
          [ 5, 65, 58, 73]]]])


In [22]:
tensor_new.flatten(start_dim=1)

tensor([[24, 58, 53, 34, 55, 59, 49,  5, 95, 43,  1, 82, 45, 35, 61, 41],
        [95,  6, 34, 74, 12, 17, 84, 31, 30, 48, 78,  2, 51, 43, 21, 50],
        [19, 45, 93, 62, 98, 35, 97, 53, 21,  2, 59, 73, 22, 58, 92, 64]])