In [1]:
import torch
import numpy as np

In [4]:
tensor_1 = torch.randint(0,100,(3,3))
tensor_2 = torch.randint(0,100,(3,3))
tensor_3 = torch.randint(0,100,(3,3))

print(tensor_1)
print(tensor_2)
print(tensor_3)

tensor([[66, 89, 72],
        [21, 56, 56],
        [45, 57, 87]])
tensor([[77, 54, 14],
        [37, 70, 95],
        [20, 13, 18]])
tensor([[68, 91, 77],
        [92,  7, 99],
        [84, 30,  6]])


In [5]:
tensor_1+2

tensor([[68, 91, 74],
        [23, 58, 58],
        [47, 59, 89]])