In [1]:
import torch
import numpy as np

In [22]:
tensor_1 = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
],dtype=torch.float32,)

print("Tensor shape : ",tensor_1.shape)
print("Tensor device  : " , tensor_1.device)

Tensor shape :  torch.Size([3, 4])
Tensor device  :  cpu


In [23]:
print(tensor_1.size())
print(tensor_1.shape)

torch.Size([3, 4])
torch.Size([3, 4])


In [24]:
#number 
tensor_1.numel()

12

In [29]:
print(tensor_1.reshape([1,12]))
print()
print(tensor_1.reshape([2,6]))
print()

print(tensor_1.reshape([3,4]))

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [31]:
tensor_1.reshape(2,2,3)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [35]:
tensor_1.reshape([1,12]).squeeze()

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [37]:
tensor_1.reshape([1,12]).squeeze().unsqueeze(dim=0)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [49]:
def flatten(t):
    t = t.reshape(-1)
    return t

In [50]:
f_tensor = flatten(tensor_1)
print(f_tensor)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [52]:
tensor_1.size()

torch.Size([3, 4])