In [37]:
import torch
import numpy as np

In [25]:
ts = torch.Tensor([1,2,4]).cuda()
ts2 = torch.tensor([1,5,7])

print(ts.dtype)
print(ts.device)
print(ts.layout)

torch.float32
cuda:0
torch.strided


In [34]:
identity = torch.eye(2,2)
print(identity)

zeros  = torch.zeros(2,3)
print(zeros)

random_num = torch.rand(2,2)
print(random_num)

tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.8704, 0.8553],
        [0.9628, 0.1056]])


In [39]:
np_arr = np.array([1,2,3])

In [41]:
t1 = torch.Tensor(np_arr) # Class constructor function
print(t1)

t2 = torch.as_tensor(np_arr) # Factory function
print(t2)

t3 = torch.as_tensor(np_arr)
print(t3)

t4 = torch.from_numpy(np_arr)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


tensor([1., 2., 4.], device='cuda:0')
